<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'No' => 'No',
    'Yes' => 'Sí',
    'Add new' => 'Añadir nuevo',
    'Administrators' => 'Administradores',
    'An email has been sent to {email} with further instructions.' => 'Se ha enviado un email a {email} con instrucciones.',
    'Are you sure you want to delete this item?' => '¿Está seguro que desea eliminar este elemento?',
    'Back' => 'Atrás',
    'Change your connection details, such as username and password.' => 'Ajuste sus parámetros de conexión, como nombre de usuario y contraseña.',
    'Continue' => 'Continuar',
    'Create' => 'Crear',
    'Create and return' => 'Crear y volver',
    'Data successfully saved.' => 'Datos guardados correctamente.',
    'Debug info' => 'Información técnica',
    'Delete' => 'Eliminar',
    'Edit' => 'Editar',
    'Email' => 'Email',
    'Email could not be sent. Please try again later, and contact us if the problem persists.' => 'El email no ha podido ser enviado. Por favor, inténtelo de nuevo, y contacte con nosotros en caso de que el problema persista.',
    'Forgot your password?' => 'No recuerdo mi contraseña',
    'Hello {username},' => 'Hola, {username}',
    'Help' => 'Ayuda',
    'Home' => 'Inicio',
    'In order to reset your password, please enter your email address:' => 'Para restablecer su contraseña, por favor introduzca su dirección de email:',
    'Invalid password reset token.' => 'Parámetro de restablecimiento de contraseña incorrecto.',
    'Invalid username or password.' => 'Nombre de usuario y/o contraseña incorrectos.',
    'Items per page' => 'Elementos por página',
    'Leave blank to keep current password.' => 'En blanco para mantener la contraseña actual.',
    'Leave blank to keep the current password.' => 'Dejar en blanco para mantener contraseña actual.',
    'Log in' => 'Entrar',
    'Login' => 'Entrar',
    'Logout' => 'Salir',
    'Missing password reset token.' => 'Falta el parámetro de restablecimiento de contraseña.',
    'New' => 'Nuevo',
    'No matching user found.' => 'No se ha encontrado ningún usuario que coincida.',
    'Password' => 'Contraseña',
    'Password reset' => 'Restablecer contraseña',
    'Password reset for {appName}' => 'Restablecer contraseña para {appName}',
    'Password successfully reset.' => 'Contraseña cambiada correctamente.',
    'Please fix the errors marked in red below.' => 'Por favor, corrija los errores marcados en rojo.',
    'Please follow the link below to reset your password:' => 'Por favor, clique en el enlace para restablecer su contraseña:',
    'Please log in to access the admin area' => 'Por favor, identifíquese para acceder al área de administración.',
    'Profile settings' => 'Ajustes de perfil',
    'Provided token is invalid or has expired. Please {a}try again{/a}.' => 'El parámetro de restablecimiento de contraseña no es válido o ha caducado. Por favor, {a}repita el proceso{/a}.',
    'Remember me in this computer' => 'Recuérdame en este ordenador',
    'Repeat password' => 'Repetir contraseña',
    'Request password reset' => 'Solicitar restablecimento de contraseña',
    'Save' => 'Guardar',
    'Save and return' => 'Guardar y volver',
    'Update' => 'Actualizar',
    'Used for password reset.' => 'Se usa para restablecer contraseña.',
    'Username' => 'Nombre de usuario',
    'Users' => 'Usuarios',
    'Welcome, {username}. Please choose your new password:' => 'Hola, {username}. Por favor, elige tu nueva contraseña:',
    '{attribute} "{value}" is already in use.' => '{attribute} "{value}" ya está en uso.',
];
