<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new' => '',
    'Administrators' => '',
    'An email has been sent to {email} with further instructions.' => '',
    'Are you sure you want to delete this item?' => '',
    'Back' => '',
    'Change your connection details, such as username and password.' => '',
    'Continue' => '',
    'Create' => '',
    'Create and return' => '',
    'Data successfully saved.' => '',
    'Debug info' => '',
    'Delete' => '',
    'Edit' => '',
    'Email' => '',
    'Email could not be sent. Please try again later, and contact us if the problem persists.' => '',
    'Forgot your password?' => '',
    'Hello {username},' => '',
    'Help' => '',
    'Home' => '',
    'In order to reset your password, please enter your email address:' => '',
    'Invalid password reset token.' => '',
    'Invalid username or password.' => '',
    'Items per page' => '',
    'Leave blank to keep current password.' => '',
    'Leave blank to keep the current password.' => '',
    'Log in' => '',
    'Login' => '',
    'Logout' => '',
    'Missing password reset token.' => '',
    'New' => '',
    'No matching user found.' => '',
    'Password' => '',
    'Password reset' => '',
    'Password reset for {appName}' => '',
    'Password successfully reset.' => '',
    'Please fix the errors marked in red below.' => '',
    'Please follow the link below to reset your password:' => '',
    'Please log in to access the admin area' => '',
    'Profile settings' => '',
    'Provided token is invalid or has expired. Please {a}try again{/a}.' => '',
    'Remember me in this computer' => '',
    'Repeat password' => '',
    'Request password reset' => '',
    'Save' => '',
    'Save and return' => '',
    'Update' => '',
    'Used for password reset.' => '',
    'Username' => '',
    'Users' => '',
    'Welcome, {username}. Please choose your new password:' => '',
    '{attribute} "{value}" is already in use.' => '',
    'No' => '',
    'Yes' => '',
];
